export interface TechnicalAccount {
  name: string;
  role: string;
  mail: string;
  enable: boolean;
  uuid: string;
  modificationDate: number;
  creationDate: number;
  domain: string;
  domainName: string;
  locked: boolean;
}

export interface TechnicalAccountDetails {
  uuid: string;
  creationDate: number;
  modificationDate: number;
  domain: string;
  domainName: string;
  locked: boolean;
  enable: boolean;
  name: string;
  mail: string;
  permissions: string[];
  role: string;
}

export interface TechnicalAccountCreation {
  enable: boolean;
  mail: string;
  name: string;
  password: string;
  role: string;
}

export enum PermissionType {
  ANONYMOUS_SHARE_ENTRIES_CREATE = 'ANONYMOUS_SHARE_ENTRIES_CREATE',
  ANONYMOUS_SHARE_ENTRIES_DELETE = 'ANONYMOUS_SHARE_ENTRIES_DELETE',
  ANONYMOUS_SHARE_ENTRIES_DOWNLOAD = 'ANONYMOUS_SHARE_ENTRIES_DOWNLOAD',
  ANONYMOUS_SHARE_ENTRIES_DOWNLOAD_THUMBNAIL = 'ANONYMOUS_SHARE_ENTRIES_DOWNLOAD_THUMBNAIL',
  ANONYMOUS_SHARE_ENTRIES_GET = 'ANONYMOUS_SHARE_ENTRIES_GET',
  ANONYMOUS_SHARE_ENTRIES_LIST = 'ANONYMOUS_SHARE_ENTRIES_LIST',
  ANONYMOUS_SHARE_ENTRIES_UPDATE = 'ANONYMOUS_SHARE_ENTRIES_UPDATE',
  ASYNC_TASK_CREATE = 'ASYNC_TASK_CREATE',
  ASYNC_TASK_DELETE = 'ASYNC_TASK_DELETE',
  ASYNC_TASK_GET = 'ASYNC_TASK_GET',
  ASYNC_TASK_LIST = 'ASYNC_TASK_LIST',
  ASYNC_TASK_UPDATE = 'ASYNC_TASK_UPDATE',
  AUDIT_LIST = 'AUDIT_LIST',
  DOCUMENT_ENTRIES_CREATE = 'DOCUMENT_ENTRIES_CREATE',
  DOCUMENT_ENTRIES_DELETE = 'DOCUMENT_ENTRIES_DELETE',
  DOCUMENT_ENTRIES_DOWNLOAD = 'DOCUMENT_ENTRIES_DOWNLOAD',
  DOCUMENT_ENTRIES_DOWNLOAD_THUMBNAIL = 'DOCUMENT_ENTRIES_DOWNLOAD_THUMBNAIL',
  DOCUMENT_ENTRIES_GET = 'DOCUMENT_ENTRIES_GET',
  DOCUMENT_ENTRIES_LIST = 'DOCUMENT_ENTRIES_LIST',
  DOCUMENT_ENTRIES_UPDATE = 'DOCUMENT_ENTRIES_UPDATE',
  DRIVE_CREATE = 'DRIVE_CREATE',
  DRIVE_DELETE = 'DRIVE_DELETE',
  DRIVE_GET = 'DRIVE_GET',
  DRIVE_LIST = 'DRIVE_LIST',
  DRIVE_UPDATE = 'DRIVE_UPDATE',
  GUESTS_CREATE = 'GUESTS_CREATE',
  GUESTS_DELETE = 'GUESTS_DELETE',
  GUESTS_GET = 'GUESTS_GET',
  GUESTS_LIST = 'GUESTS_LIST',
  GUESTS_MODERATOR_CREATE = 'GUESTS_MODERATOR_CREATE',
  GUESTS_MODERATOR_DELETE = 'GUESTS_MODERATOR_DELETE',
  GUESTS_MODERATOR_GET = 'GUESTS_MODERATOR_GET',
  GUESTS_MODERATOR_LIST = 'GUESTS_MODERATOR_LIST',
  GUESTS_MODERATOR_UPDATE = 'GUESTS_MODERATOR_UPDATE',
  GUESTS_UPDATE = 'GUESTS_UPDATE',
  LISTS_CREATE = 'LISTS_CREATE',
  LISTS_DELETE = 'LISTS_DELETE',
  LISTS_GET = 'LISTS_GET',
  LISTS_LIST = 'LISTS_LIST',
  LISTS_UPDATE = 'LISTS_UPDATE',
  QUOTA_CREATE = 'QUOTA_CREATE',
  QUOTA_GET = 'QUOTA_GET',
  QUOTA_LIST = 'QUOTA_LIST',
  QUOTA_UPDATE = 'QUOTA_UPDATE',
  SAFE_DETAIL_CREATE = 'SAFE_DETAIL_CREATE',
  SAFE_DETAIL_DELETE = 'SAFE_DETAIL_DELETE',
  SAFE_DETAIL_GET = 'SAFE_DETAIL_GET',
  SAFE_DETAIL_LIST = 'SAFE_DETAIL_LIST',
  SHARED_SPACE_NODE_CREATE = 'SHARED_SPACE_NODE_CREATE',
  SHARED_SPACE_NODE_DELETE = 'SHARED_SPACE_NODE_DELETE',
  SHARED_SPACE_NODE_GET = 'SHARED_SPACE_NODE_GET',
  SHARED_SPACE_NODE_LIST = 'SHARED_SPACE_NODE_LIST',
  SHARED_SPACE_NODE_UPDATE = 'SHARED_SPACE_NODE_UPDATE',
  SHARED_SPACE_PERMISSION_CREATE = 'SHARED_SPACE_PERMISSION_CREATE',
  SHARED_SPACE_PERMISSION_DELETE = 'SHARED_SPACE_PERMISSION_DELETE',
  SHARED_SPACE_PERMISSION_GET = 'SHARED_SPACE_PERMISSION_GET',
  SHARED_SPACE_PERMISSION_LIST = 'SHARED_SPACE_PERMISSION_LIST',
  SHARED_SPACE_PERMISSION_UPDATE = 'SHARED_SPACE_PERMISSION_UPDATE',
  SHARED_SPACE_ROLE_CREATE = 'SHARED_SPACE_ROLE_CREATE',
  SHARED_SPACE_ROLE_DELETE = 'SHARED_SPACE_ROLE_DELETE',
  SHARED_SPACE_ROLE_GET = 'SHARED_SPACE_ROLE_GET',
  SHARED_SPACE_ROLE_LIST = 'SHARED_SPACE_ROLE_LIST',
  SHARED_SPACE_ROLE_UPDATE = 'SHARED_SPACE_ROLE_UPDATE',
  SHARE_ENTRIES_CREATE = 'SHARE_ENTRIES_CREATE',
  SHARE_ENTRIES_DELETE = 'SHARE_ENTRIES_DELETE',
  SHARE_ENTRIES_DOWNLOAD = 'SHARE_ENTRIES_DOWNLOAD',
  SHARE_ENTRIES_DOWNLOAD_THUMBNAIL = 'SHARE_ENTRIES_DOWNLOAD_THUMBNAIL',
  SHARE_ENTRIES_GET = 'SHARE_ENTRIES_GET',
  SHARE_ENTRIES_LIST = 'SHARE_ENTRIES_LIST',
  SHARE_ENTRIES_UPDATE = 'SHARE_ENTRIES_UPDATE',
  SHARE_ENTRY_GROUPS_DELETE = 'SHARE_ENTRY_GROUPS_DELETE',
  SHARE_ENTRY_GROUPS_GET = 'SHARE_ENTRY_GROUPS_GET',
  SHARE_ENTRY_GROUPS_LIST = 'SHARE_ENTRY_GROUPS_LIST',
  SHARE_ENTRY_GROUPS_UPDATE = 'SHARE_ENTRY_GROUPS_UPDATE',
  STATISTIC_GET = 'STATISTIC_GET',
  STATISTIC_LIST = 'STATISTIC_LIST',
  THREADS_CREATE = 'THREADS_CREATE',
  THREADS_DELETE = 'THREADS_DELETE',
  THREADS_GET = 'THREADS_GET',
  THREADS_LIST = 'THREADS_LIST',
  THREADS_UPDATE = 'THREADS_UPDATE',
  THREAD_ENTRIES_CREATE = 'THREAD_ENTRIES_CREATE',
  THREAD_ENTRIES_DELETE = 'THREAD_ENTRIES_DELETE',
  THREAD_ENTRIES_DOWNLOAD = 'THREAD_ENTRIES_DOWNLOAD',
  THREAD_ENTRIES_DOWNLOAD_THUMBNAIL = 'THREAD_ENTRIES_DOWNLOAD_THUMBNAIL',
  THREAD_ENTRIES_GET = 'THREAD_ENTRIES_GET',
  THREAD_ENTRIES_LIST = 'THREAD_ENTRIES_LIST',
  THREAD_ENTRIES_UPDATE = 'THREAD_ENTRIES_UPDATE',
  THREAD_MEMBERS_CREATE = 'THREAD_MEMBERS_CREATE',
  THREAD_MEMBERS_DELETE = 'THREAD_MEMBERS_DELETE',
  THREAD_MEMBERS_GET = 'THREAD_MEMBERS_GET',
  THREAD_MEMBERS_LIST = 'THREAD_MEMBERS_LIST',
  THREAD_MEMBERS_UPDATE = 'THREAD_MEMBERS_UPDATE',
  UPLOAD_PROPOSITION_CREATE = 'UPLOAD_PROPOSITION_CREATE',
  UPLOAD_PROPOSITION_DELETE = 'UPLOAD_PROPOSITION_DELETE',
  UPLOAD_PROPOSITION_EXCEPTION_RULE_CREATE = 'UPLOAD_PROPOSITION_EXCEPTION_RULE_CREATE',
  UPLOAD_PROPOSITION_EXCEPTION_RULE_DELETE = 'UPLOAD_PROPOSITION_EXCEPTION_RULE_DELETE',
  UPLOAD_PROPOSITION_EXCEPTION_RULE_GET = 'UPLOAD_PROPOSITION_EXCEPTION_RULE_GET',
  UPLOAD_PROPOSITION_EXCEPTION_RULE_LIST = 'UPLOAD_PROPOSITION_EXCEPTION_RULE_LIST',
  UPLOAD_PROPOSITION_EXCEPTION_RULE_UPDATE = 'UPLOAD_PROPOSITION_EXCEPTION_RULE_UPDATE',
  UPLOAD_PROPOSITION_GET = 'UPLOAD_PROPOSITION_GET',
  UPLOAD_PROPOSITION_LIST = 'UPLOAD_PROPOSITION_LIST',
  UPLOAD_PROPOSITION_UPDATE = 'UPLOAD_PROPOSITION_UPDATE',
  UPLOAD_REQUEST_CREATE = 'UPLOAD_REQUEST_CREATE',
  UPLOAD_REQUEST_DELETE = 'UPLOAD_REQUEST_DELETE',
  UPLOAD_REQUEST_ENTRIES_CREATE = 'UPLOAD_REQUEST_ENTRIES_CREATE',
  UPLOAD_REQUEST_ENTRIES_DELETE = 'UPLOAD_REQUEST_ENTRIES_DELETE',
  UPLOAD_REQUEST_ENTRIES_DOWNLOAD = 'UPLOAD_REQUEST_ENTRIES_DOWNLOAD',
  UPLOAD_REQUEST_ENTRIES_DOWNLOAD_THUMBNAIL = 'UPLOAD_REQUEST_ENTRIES_DOWNLOAD_THUMBNAIL',
  UPLOAD_REQUEST_ENTRIES_GET = 'UPLOAD_REQUEST_ENTRIES_GET',
  UPLOAD_REQUEST_ENTRIES_LIST = 'UPLOAD_REQUEST_ENTRIES_LIST',
  UPLOAD_REQUEST_ENTRIES_UPDATE = 'UPLOAD_REQUEST_ENTRIES_UPDATE',
  UPLOAD_REQUEST_GET = 'UPLOAD_REQUEST_GET',
  UPLOAD_REQUEST_LIST = 'UPLOAD_REQUEST_LIST',
  UPLOAD_REQUEST_TEMPLATE_CREATE = 'UPLOAD_REQUEST_TEMPLATE_CREATE',
  UPLOAD_REQUEST_TEMPLATE_DELETE = 'UPLOAD_REQUEST_TEMPLATE_DELETE',
  UPLOAD_REQUEST_TEMPLATE_GET = 'UPLOAD_REQUEST_TEMPLATE_GET',
  UPLOAD_REQUEST_TEMPLATE_LIST = 'UPLOAD_REQUEST_TEMPLATE_LIST',
  UPLOAD_REQUEST_TEMPLATE_UPDATE = 'UPLOAD_REQUEST_TEMPLATE_UPDATE',
  UPLOAD_REQUEST_UPDATE = 'UPLOAD_REQUEST_UPDATE',
  UPLOAD_REQUEST_URL_CREATE = 'UPLOAD_REQUEST_URL_CREATE',
  UPLOAD_REQUEST_URL_DELETE = 'UPLOAD_REQUEST_URL_DELETE',
  UPLOAD_REQUEST_URL_GET = 'UPLOAD_REQUEST_URL_GET',
  UPLOAD_REQUEST_URL_LIST = 'UPLOAD_REQUEST_URL_LIST',
  UPLOAD_REQUEST_URL_UPDATE = 'UPLOAD_REQUEST_URL_UPDATE',
}
