export const MAIL_CONTENT_TYPE = {
  FILE_WARN_OWNER_BEFORE_FILE_EXPIRY: 'Một tệp đang sắp bị xóa vì nó sẽ hết hạn',
  GUEST_ACCOUNT_NEW_CREATION: 'Một khách mới nhận một liên kết kích hoạt tài khoản của mình',
  GUEST_ACCOUNT_RESET_PASSWORD_LINK: 'Một khách nhận liên kết đặt lại mật khẩu',
  GUEST_WARN_GUEST_ABOUT_HIS_PASSWORD_RESET: 'Mật khẩu tài khoản khách đã được thay đổi',
  GUEST_WARN_OWNER_ABOUT_GUEST_EXPIRATION: 'Tài khoản khách sẽ hết hạn sớm',
  GUEST_ACCOUNT_RESET_PASSWORD_FOR_4_0: 'Thay đổi mật khẩu khách do cải thiện bảo mật',
  SHARE_FILE_DOWNLOAD: 'Người nhận đã tải xuống tệp chia sẻ',
  SHARE_FILE_SHARE_DELETED: 'Người gửi đã xóa tệp chia sẻ của mình',
  SHARE_NEW_SHARE_ACKNOWLEDGEMENT_FOR_SENDER: 'Người gửi nhận được một bản tóm tắt về việc chia sẻ tệp của mình',
  SHARE_NEW_SHARE_FOR_RECIPIENT: 'Người nhận nhận được liên kết chia sẻ tệp',
  SHARE_WARN_RECIPIENT_BEFORE_EXPIRY: 'Chia sẻ tệp của người gửi sắp hết hạn',
  SHARE_WARN_UNDOWNLOADED_FILESHARES: 'Nhắc nhở chia sẻ tệp chưa được tải xuống',
  SHARE_WARN_SENDER_ABOUT_SHARE_EXPIRATION_WITHOUT_DOWNLOAD: 'Một chia sẻ sẽ hết hạn sớm mà không được tải xuống',
  SHARE_WARN_RECIPIENT_ABOUT_EXPIRED_SHARE: 'Chia sẻ đã hết hạn và bị hệ thống xóa',
  SHARE_ANONYMOUS_RESET_PASSWORD: 'Mật khẩu chia sẻ ẩn danh đã được đặt lại',
  UPLOAD_REQUEST_CLOSED_BY_CREATOR: 'Người tạo đã đóng yêu cầu tải lên',
  UPLOAD_REQUEST_CLOSED_BY_RECIPIENT: 'Người nhận đã đóng yêu cầu tải lên của người tạo',
  UPLOAD_REQUEST_FILE_DELETED_BY_RECIPIENT: 'Người nhận đã xóa một tệp trong yêu cầu tải lên',
  UPLOAD_REQUEST_FILE_DELETED_BY_OWNER: 'Người tạo yêu cầu tải lên đã xóa một tệp',
  UPLOAD_REQUEST_UNAVAILABLE_SPACE: 'Người nhận không thể tải lên tệp của mình do không đủ không gian',
  UPLOAD_REQUEST_UPLOADED_FILE: 'Người nhận đã tải lên một tệp trong yêu cầu tải lên',
  UPLOAD_REQUEST_WARN_BEFORE_EXPIRY: 'Một yêu cầu tải lên sẽ sắp bị đóng',
  UPLOAD_REQUEST_WARN_EXPIRY: 'Một yêu cầu tải lên đã bị đóng',
  UPLOAD_REQUEST_ACTIVATED_FOR_OWNER: 'Một yêu cầu tải lên đã được kích hoạt cho người tạo',
  UPLOAD_REQUEST_ACTIVATED_FOR_RECIPIENT: 'Một yêu cầu tải lên đã được kích hoạt cho người nhận',
  UPLOAD_REQUEST_CLOSED_BY_OWNER: 'Yêu cầu tải lên đã bị đóng bởi người tạo',
  UPLOAD_REQUEST_CREATED: 'Một yêu cầu tải lên đã được tạo',
  UPLOAD_REQUEST_FILE_DELTED_BY_OWNER: 'Người tạo yêu cầu tải lên đã xóa một tệp',
  UPLOAD_REQUEST_PASSWORD_RENEWAL: 'Mật khẩu của yêu cầu tải lên đã được đổi',
  UPLOAD_REQUEST_PASSWORD_REMOVED: 'Mật khẩu của yêu cầu tải lên đã bị xóa',
  UPLOAD_REQUEST_REMINDER: 'Nhắc nhở người nhận về yêu cầu tải lên',
  UPLOAD_REQUEST_UPDATED_SETTINGS: 'Các thiết lập liên quan đến yêu cầu tải lên đã được cập nhật',
  UPLOAD_REQUEST_RECIPIENT_REMOVED: 'Một liên hệ cụ thể trong yêu cầu tải lên đã bị xóa',
  WORKGROUP_WARN_NEW_MEMBER: 'Một người dùng đã được thêm vào nhóm làm việc',
  WORKGROUP_WARN_UPDATED_MEMBER: 'Quyền của một thành viên trong nhóm làm việc đã được cập nhật',
  WORKGROUP_WARN_DELETED_MEMBER: 'Một thành viên đã bị xóa khỏi nhóm làm việc',
  WORKGROUP_WARN_DELETED_WORKGROUP: 'Một nhóm làm việc đã bị xóa',
  ACCOUNT_OWNER_WARN_JWT_PERMANENT_TOKEN_CREATED:
    'Người dùng nhận thông báo khi quản trị viên tạo một mã thông báo truy cập cố định (JWT) vĩnh viễn cho tài khoản của mình',
  ACCOUNT_OWNER_WARN_JWT_PERMANENT_TOKEN_DELETED:
    'Người dùng nhận thông báo khi quản trị viên xóa một mã thông báo truy cập cố định (JWT) vĩnh viễn cho tài khoản của mình',
  DRIVE_WARN_DELETED_MEMBER: 'Một thành viên đã bị xóa khỏi DRIVE',
  DRIVE_WARN_NEW_MEMBER: 'Một người dùng đã được thêm vào DRIVE',
  DRIVE_WARN_UPDATED_MEMBER: 'Quyền của một thành viên trên DRIVE đã được cập nhật',
  WORK_SPACE_WARN_DELETED: 'Một không gian làm việc đã bị xóa',
  WORK_SPACE_WARN_DELETED_MEMBER: 'Một thành viên đã bị xóa khỏi không gian làm việc',
  WORK_SPACE_WARN_NEW_MEMBER: 'Một người dùng đã được thêm vào không gian làm việc',
  WORK_SPACE_WARN_UPDATED_MEMBER: 'Quyền của một thành viên trong không gian làm việc đã được cập nhật',
};
