export const PERMISSIONS = Object.freeze({
  DOMAINS: {
    VIEW: 'DOMAINS.VIEW',
    MANAGE_DOMAINS: 'DOMAINS.MANAGE_DOMAINS',
    FUNCTIONALITIES: 'DOMAINS.FUNCTIONALITIES'
  },
  USERS: {
    VIEW: 'USERS.VIEW',
    MANAGE_USERS: 'USERS.MANAGE_USERS',
    INCONSISTENT_USERS: 'USERS.INCONSISTENT_USERS',
    TECHNICAL_ACCOUNTS: 'USERS.TECHNICAL_ACCOUNTS'
  },
  WORKGROUPS: {
    VIEW: 'WORKGROUPS.VIEW'
  },
  MAILING_LISTS: {
    VIEW: 'MAILING_LISTS.VIEW'
  },
  HISTORY: {
    VIEW: 'HISTORY.VIEW'
  },
  MAILS: {
    VIEW: 'MAILS.VIEW',
    CONFIGURATION: 'MAILS.CONFIGURATION',
    LAYOUT: 'MAILS.LAYOUT',
    FOOTER: 'MAILS.FOOTER',
    CONTENT: 'MAILS.CONTENT',
    ACTIVATION: 'MAILS.ACTIVATION'
  },
  UPGRADE_TASKS: {
    VIEW: 'UPGRADE_TASKS.VIEW'
  }
});
